language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t rfblue2/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rfblue2/docker-react npm run test -- --coverage